/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package DATANET.GIU;

import DATANET.GIU.OPCIONES.SALIR;
import java.util.HashSet;
import java.util.Set;
import pe.edu.upn.datanet.Conexion;

/**
 *
 * @author Màximo
 */
public class INTERFAZ extends javax.swing.JFrame {

    /**
     * Creates new form INTERFAZ
     */
    public INTERFAZ() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BACKGROUND = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        txtPassword = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);

        BACKGROUND.setBackground(new java.awt.Color(255, 255, 255));
        BACKGROUND.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        BACKGROUND.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setIcon(new javax.swing.ImageIcon("C:\\Users\\Màximo\\Desktop\\DATANET\\DATANET\\IMAGENES\\ELIMINAR_CUADRADO_48.png")); // NOI18N
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });
        BACKGROUND.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel5.setFont(new java.awt.Font("Roboto Black", 0, 48)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("DATANET");
        BACKGROUND.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 500, -1, -1));

        jLabel3.setFont(new java.awt.Font("Roboto Black", 0, 24)); // NOI18N
        jLabel3.setText("USUARIO");
        BACKGROUND.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 310, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Màximo\\Desktop\\DATANET\\DATANET\\IMAGENES\\LOGO.png")); // NOI18N
        BACKGROUND.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, 320, 300));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Màximo\\Desktop\\DATANET\\DATANET\\IMAGENES\\FONDO.jpg")); // NOI18N
        BACKGROUND.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 470, 770));

        jLabel6.setFont(new java.awt.Font("Roboto Black", 0, 36)); // NOI18N
        jLabel6.setText("INICIAR SESIÓN");
        BACKGROUND.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 210, -1, -1));

        txtUsuario.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        txtUsuario.setToolTipText("Ingrese su nombre de usuario");
        txtUsuario.setBorder(null);
        txtUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsuarioActionPerformed(evt);
            }
        });
        BACKGROUND.add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 350, 380, 50));
        BACKGROUND.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 430, -1, -1));

        txtPassword.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        txtPassword.setBorder(null);
        txtPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPasswordActionPerformed(evt);
            }
        });
        BACKGROUND.add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 480, 380, 50));

        jSeparator2.setPreferredSize(new java.awt.Dimension(0, 90));
        BACKGROUND.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 400, 380, 20));

        jLabel7.setFont(new java.awt.Font("Roboto Black", 0, 24)); // NOI18N
        jLabel7.setText("CONTRASEÑA");
        BACKGROUND.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 440, -1, -1));

        jSeparator3.setPreferredSize(new java.awt.Dimension(0, 90));
        BACKGROUND.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 530, 380, 20));

        jLabel8.setFont(new java.awt.Font("Roboto Medium", 0, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("INGRESAR");
        BACKGROUND.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 640, -1, -1));

        jButton1.setBackground(new java.awt.Color(40, 171, 250));
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        BACKGROUND.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 620, 230, 70));

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\Màximo\\Desktop\\DATANET\\DATANET\\IMAGENES\\images.png")); // NOI18N
        BACKGROUND.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 30, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BACKGROUND, javax.swing.GroupLayout.PREFERRED_SIZE, 1140, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BACKGROUND, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsuarioActionPerformed

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        SALIR f = new SALIR();
        f.setVisible (true);
    }//GEN-LAST:event_jLabel9MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Conexion con = new Conexion();
        con.establecerconexion();

        if (con.Login(txtUsuario.getText(), txtPassword.getText()) == 1) {
            DATANET.GIU.OPCIONES.ACEPTAR_INGRESO g = new DATANET.GIU.OPCIONES.ACEPTAR_INGRESO ();
            g.setVisible(true);
            this.dispose();
        }else{
            DATANET.GIU.OPCIONES.NOACEPTAR_INGRESO o = new DATANET.GIU.OPCIONES.NOACEPTAR_INGRESO ();
            o.setVisible(true);
            this.dispose();
        }


    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPasswordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(INTERFAZ.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(INTERFAZ.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(INTERFAZ.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(INTERFAZ.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new INTERFAZ().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BACKGROUND;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextField txtPassword;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
