/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package DATANET.GIU;
import DATANET.BL.distritoBL;
import DATANET.BL.proveedorBL;
import static java.lang.Short.toString;
import java.sql.ResultSet;
import java.util.Set;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import pe.edu.upn.datanet.Conexion;


/**
 *
 * @author Màximo
 */
public class Proveedor extends javax.swing.JFrame {
    
    DefaultTableModel mode1;
    /**
     * Creates new form Distrito
     */
    public Proveedor() {
        initComponents();
        String[] titulos = {"CODIGO", "RUC", "NOMBRE", "DIRECCION", "CODIGO DEL DISTRITO", "TELEFONO", "CELULAR"};
        mode1 = new DefaultTableModel(null, titulos);
        tblProveedor.setModel(mode1);
        this.mostrardatos();
        limpiar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtDireccion_Proveedor = new javax.swing.JTextField();
        btnAgregar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProveedor = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtCod_Proveedor = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtRUC_Proveedor = new javax.swing.JTextField();
        txtNom_Proveedor = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtCel_Proveedor = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtCod_Distrito = new javax.swing.JTextField();
        txtTel_Proveedor = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        txtDireccion_Proveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDireccion_ProveedorActionPerformed(evt);
            }
        });
        jPanel1.add(txtDireccion_Proveedor);
        txtDireccion_Proveedor.setBounds(190, 280, 360, 32);

        btnAgregar.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        btnAgregar.setIcon(new javax.swing.ImageIcon("C:\\Users\\Màximo\\Desktop\\DATANET\\DATANET\\IMAGENES\\OK_16.png")); // NOI18N
        btnAgregar.setText("AGREGAR");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        jPanel1.add(btnAgregar);
        btnAgregar.setBounds(110, 460, 125, 41);

        btnModificar.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        btnModificar.setIcon(new javax.swing.ImageIcon("C:\\Users\\Màximo\\Desktop\\DATANET\\DATANET\\IMAGENES\\EDITAR_16.png")); // NOI18N
        btnModificar.setText("MODIFICAR");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });
        jPanel1.add(btnModificar);
        btnModificar.setBounds(250, 460, 125, 41);

        btnEliminar.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        btnEliminar.setIcon(new javax.swing.ImageIcon("C:\\Users\\Màximo\\Desktop\\DATANET\\DATANET\\IMAGENES\\ELIMINAR_CIRCULO_16.png")); // NOI18N
        btnEliminar.setText("ELIMINAR");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        jPanel1.add(btnEliminar);
        btnEliminar.setBounds(390, 460, 125, 41);

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel3.setText("DIRECCION:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(69, 280, 108, 24);

        tblProveedor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblProveedor.setAutoscrolls(false);
        tblProveedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblProveedorMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblProveedor);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(6, 514, 600, 260);

        jLabel1.setFont(new java.awt.Font("Roboto Medium", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("PROVEEDOR");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(160, 50, 300, 57);

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setText("COD. PROVEEDOR:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(10, 170, 180, 24);

        txtCod_Proveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCod_ProveedorActionPerformed(evt);
            }
        });
        jPanel1.add(txtCod_Proveedor);
        txtCod_Proveedor.setBounds(190, 160, 215, 32);

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\Màximo\\Desktop\\DATANET\\DATANET\\IMAGENES\\VOLVER.png")); // NOI18N
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel4);
        jLabel4.setBounds(570, 10, 30, 60);

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\Màximo\\Desktop\\DATANET\\DATANET\\IMAGENES\\FONDO.jpg")); // NOI18N
        jLabel5.setText("jLabel5");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(0, 0, 610, 150);

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel6.setText("RUC PROVEEDOR:");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(10, 210, 170, 24);

        txtRUC_Proveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRUC_ProveedorActionPerformed(evt);
            }
        });
        jPanel1.add(txtRUC_Proveedor);
        txtRUC_Proveedor.setBounds(190, 200, 360, 32);

        txtNom_Proveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNom_ProveedorActionPerformed(evt);
            }
        });
        jPanel1.add(txtNom_Proveedor);
        txtNom_Proveedor.setBounds(190, 240, 360, 32);

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel7.setText("NOMBRE:");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(90, 240, 87, 24);

        txtCel_Proveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCel_ProveedorActionPerformed(evt);
            }
        });
        jPanel1.add(txtCel_Proveedor);
        txtCel_Proveedor.setBounds(190, 400, 360, 32);

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel8.setText("CELULAR:");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(78, 400, 100, 24);

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel9.setText("COD. DISTRITO:");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(40, 320, 150, 24);

        txtCod_Distrito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCod_DistritoActionPerformed(evt);
            }
        });
        jPanel1.add(txtCod_Distrito);
        txtCod_Distrito.setBounds(190, 320, 360, 32);

        txtTel_Proveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTel_ProveedorActionPerformed(evt);
            }
        });
        jPanel1.add(txtTel_Proveedor);
        txtTel_Proveedor.setBounds(190, 360, 360, 32);

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel10.setText("TELEFONO:");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(70, 360, 110, 24);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, 780));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtDireccion_ProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDireccion_ProveedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDireccion_ProveedorActionPerformed

    private void txtCod_ProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCod_ProveedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCod_ProveedorActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        Conexion objetoConexion = new Conexion();

        proveedorBL oProveedor = recuperarDatosGIU();

        String strSentenciaInsert = String.format("INSERT INTO Proveedor (Cod_Proveedor, RUC_Proveedor, Nom_Proveedor, Direc_Proveedor, Cod_Distrito, Telef_Proveedor, Cel_Proveedor) "
                + "VALUES ('%s', '%d', '%s','%s', '%s', '%d', '%d'", oProveedor.getCod_Proveedor(), oProveedor.getRUC_Proveedor(), oProveedor.getNom_Proveedor(), oProveedor.getDirec_Proveedor(), oProveedor.getCod_Distrito(), oProveedor.getTelef_Proveedor(), oProveedor.getCel_Proveedor());
        objetoConexion.ejecutarSentenciaSQL(strSentenciaInsert);
        this.mostrardatos();
        this.limpiar();
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void tblProveedorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblProveedorMouseClicked
        // TODO add your handling code here:
        
        if(evt.getClickCount()==1){
             JTable receptor = (JTable) evt.getSource();
            txtCod_Proveedor.setText(receptor.getModel().getValueAt(receptor.getSelectedRow(),0).toString());
            txtRUC_Proveedor.setText(receptor.getModel().getValueAt(receptor.getSelectedRow(),1).toString());
            txtNom_Proveedor.setText(receptor.getModel().getValueAt(receptor.getSelectedRow(),2).toString());
            txtDireccion_Proveedor.setText(receptor.getModel().getValueAt(receptor.getSelectedRow(),3).toString());
            txtCod_Distrito.setText(receptor.getModel().getValueAt(receptor.getSelectedRow(),4).toString());
            txtTel_Proveedor.setText(receptor.getModel().getValueAt(receptor.getSelectedRow(),5).toString());
            txtCel_Proveedor.setText(receptor.getModel().getValueAt(receptor.getSelectedRow(),6).toString());

        }
        btnAgregar.setEnabled(false);
        btnModificar.setEnabled(true);
        btnEliminar.setEnabled(true);
    }//GEN-LAST:event_tblProveedorMouseClicked

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        Conexion objconexion = new Conexion();
       proveedorBL oProveedor= recuperarDatosGIU();
        String strSentenciaInsert = String.format("DELETE FROM Proveedor WHERE Cod_Proveedor = '%s'",oProveedor.getCod_Proveedor());
        objconexion.ejecutarSentenciaSQL(strSentenciaInsert);
        this.mostrardatos();
        this.limpiar();
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        Conexion objconexion = new Conexion();
        
        proveedorBL oProveedor= recuperarDatosGIU();
        
        String strSentenciaInsert = String.format("UPDATE PROVEEDOR SET RUC_Proveedor='%s', Nom_Proveedor='%s',Direc_Proveedor='%s',Cod_Distrito='%s',Telef_Proveedor='%s',Cel_Proveedor='%s' "
                + "WHERE Cod_Proveedor = '%s'",oProveedor.getRUC_Proveedor(),oProveedor.getNom_Proveedor(),oProveedor.getDirec_Proveedor(),oProveedor.getCod_Distrito(),oProveedor.getTelef_Proveedor(),oProveedor.getCel_Proveedor(),oProveedor.getCod_Proveedor());
        objconexion.ejecutarSentenciaSQL(strSentenciaInsert);
        this.mostrardatos();
        this.limpiar();
    }//GEN-LAST:event_btnModificarActionPerformed

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        INTERFAZ_2 f = new INTERFAZ_2();
        f.setVisible (true);
        this.dispose();
    }//GEN-LAST:event_jLabel4MouseClicked

    private void txtRUC_ProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRUC_ProveedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRUC_ProveedorActionPerformed

    private void txtNom_ProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNom_ProveedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNom_ProveedorActionPerformed

    private void txtCel_ProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCel_ProveedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCel_ProveedorActionPerformed

    private void txtCod_DistritoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCod_DistritoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCod_DistritoActionPerformed

    private void txtTel_ProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTel_ProveedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTel_ProveedorActionPerformed
    
    public void mostrardatos(){
        
        while (mode1.getRowCount()>0) {
            mode1.removeRow(0);
        }
        
        Conexion objconexion = new Conexion();
        try {
            ResultSet resultado = objconexion.consultarRegistros("SELECT * FROM Proveedor");
            while (resultado.next()) {
                System.out.println(resultado.getString("Cod_Proveedor"));
                System.out.println(resultado.getString("RUC_Proveedor"));
                System.out.println(resultado.getString("Nom_Proveedor"));
                System.out.println(resultado.getString("Direc_Proveedor"));
                System.out.println(resultado.getString("Cod_Distrito"));
                System.out.println(resultado.getString("Telef_Proveedor"));
                System.out.println(resultado.getString("Cel_Proveedor"));
                Object[] oProveedor = {resultado.getString("Cod_Proveedor"), resultado.getString("RUC_Proveedor"), resultado.getString("Nom_Proveedor"), resultado.getString("Direc_Proveedor"), resultado.getString("Cod_Distrito"), resultado.getString("Telef_Proveedor"), resultado.getString("Cel_Proveedor")};
                mode1.addRow(oProveedor);
            }
        } catch (Exception e) {
            System.out.print(e);
        }
    }
    
    public proveedorBL recuperarDatosGIU() {
        proveedorBL oProveedor = new proveedorBL();

        //int Telefono = (txtTel_Proveedor.getText().isEmpty() ? 0 : Integer.parseInt(txtTel_Proveedor.getText()));
        //int RUC = (txtRUC_Proveedor.getText().isEmpty() ? 0 : Integer.parseInt(txtRUC_Proveedor.getText()));
        //int Celular = (txtCel_Proveedor.getText().isEmpty() ? 0 : Integer.parseInt(txtCel_Proveedor.getText()));

        oProveedor.setCod_Proveedor(txtCod_Proveedor.getText());
        oProveedor.setRUC_Proveedor(Integer.parseInt(txtRUC_Proveedor.getText()));
        oProveedor.setNom_Proveedor(txtNom_Proveedor.getText());
        oProveedor.setDirec_Proveedor(txtDireccion_Proveedor.getText());
        oProveedor.setCod_Distrito(txtCod_Distrito.getText());
        oProveedor.setTelef_Proveedor(Integer.parseInt(txtTel_Proveedor.getText()));
        oProveedor.setCel_Proveedor(Integer.parseInt(txtCel_Proveedor.getText()));

        return oProveedor;
    }
    
    public void limpiar(){
        txtCod_Proveedor.setText("");
        txtRUC_Proveedor.setText("");
        txtNom_Proveedor.setText("");
        txtDireccion_Proveedor.setText("");
        txtCod_Distrito.setText("");
        txtTel_Proveedor.setText("");
        txtCel_Proveedor.setText("");
        
        btnAgregar.setEnabled(true);
        btnModificar.setEnabled(false);
        btnEliminar.setEnabled(false);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Proveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Proveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Proveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Proveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Proveedor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblProveedor;
    private javax.swing.JTextField txtCel_Proveedor;
    private javax.swing.JTextField txtCod_Distrito;
    private javax.swing.JTextField txtCod_Proveedor;
    private javax.swing.JTextField txtDireccion_Proveedor;
    private javax.swing.JTextField txtNom_Proveedor;
    private javax.swing.JTextField txtRUC_Proveedor;
    private javax.swing.JTextField txtTel_Proveedor;
    // End of variables declaration//GEN-END:variables
}
