/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package DATANET.GIU;

import DATANET.BL.clienteBL;
import java.sql.ResultSet;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import pe.edu.upn.datanet.Conexion;

/**
 *
 * @author USER
 */
public class Cliente extends javax.swing.JFrame {

    DefaultTableModel mode1;

    /**
     * Creates new form frmCliente
     */
    public Cliente() {
        initComponents();
        String[] titulos = {"DNI", "RUC", "NOMBRE", "APELLIDO PATERNO", "APELLIDO MATERNO", "DIRECCION", "CODIGO DEL DISTRITO", "EDAD", "TELEFONO", "CELULAR"};
        mode1 = new DefaultTableModel(null, titulos);
        tblCliente.setModel(mode1);

        mostrarDatos();
        limpiar();
    }

    public clienteBL recuperarDatosGUI() {
        clienteBL oClientes = new clienteBL();


        oClientes.setDni_Clientes(txtDNI.getText().isEmpty() ? 0 : Integer.parseInt(txtDNI.getText()));
        oClientes.setRUC_Clientes(txtRUC.getText().isEmpty() ? 0 : Integer.parseInt(txtRUC.getText()));
        oClientes.setNom_Clientes(txtNombre.getText());
        oClientes.setAppat_Clientes(txtAppat.getText());
        oClientes.setApmat_Clientes(txtApmat.getText());
        oClientes.setDirec_Clientes(txtDireccion.getText());
        oClientes.setCod_Distrito(txtCodigoDistrito.getText());
        oClientes.setFnac_Clientes(txtEdad.getText());
        oClientes.setTelef_Clientes(txtTelefono.getText().isEmpty() ? 0 : Integer.parseInt(txtTelefono.getText()));
        oClientes.setCel_Clientes(txtCelular.getText().isEmpty() ? 0 : Integer.parseInt(txtCelular.getText()));

        return oClientes;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        btnAgregar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        txtDNI = new javax.swing.JTextField();
        txtRUC = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtAppat = new javax.swing.JTextField();
        txtApmat = new javax.swing.JTextField();
        txtDireccion = new javax.swing.JTextField();
        txtCodigoDistrito = new javax.swing.JTextField();
        txtCelular = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        txtEdad = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCliente = new javax.swing.JTable();
        jLabel17 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("DNI");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 136, 60, -1));

        jLabel3.setText("RUC");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 170, 37, -1));

        jLabel4.setText("NOMBRE");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 204, 60, -1));

        jLabel5.setText("APELLIDO PATERNO");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 238, -1, -1));

        jLabel6.setText("APELLIDO MATERNO");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 272, -1, -1));

        jLabel7.setText("DIRECCION");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 300, 75, -1));

        jLabel8.setText("CODIGO DEL DISTRITO");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 334, 134, -1));

        jLabel9.setText("EDAD");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 368, 37, -1));

        jLabel10.setText("TELEFONO");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 414, 75, -1));

        jLabel11.setText("CELULAR");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 448, 59, -1));

        btnAgregar.setText("AGREGAR");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 531, -1, -1));

        btnModificar.setText("MODIFICAR");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });
        getContentPane().add(btnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(232, 531, -1, -1));

        btnEliminar.setText("ELIMINAR");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(388, 531, -1, -1));

        btnCancelar.setText("CANCELAR");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(555, 531, -1, -1));

        txtDNI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDNIActionPerformed(evt);
            }
        });
        getContentPane().add(txtDNI, new org.netbeans.lib.awtextra.AbsoluteConstraints(201, 130, 196, -1));

        txtRUC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRUCActionPerformed(evt);
            }
        });
        getContentPane().add(txtRUC, new org.netbeans.lib.awtextra.AbsoluteConstraints(201, 164, 196, -1));

        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });
        getContentPane().add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(201, 198, 196, -1));

        txtAppat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAppatActionPerformed(evt);
            }
        });
        getContentPane().add(txtAppat, new org.netbeans.lib.awtextra.AbsoluteConstraints(201, 232, 196, -1));

        txtApmat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApmatActionPerformed(evt);
            }
        });
        getContentPane().add(txtApmat, new org.netbeans.lib.awtextra.AbsoluteConstraints(201, 266, 196, -1));

        txtDireccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDireccionActionPerformed(evt);
            }
        });
        getContentPane().add(txtDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(201, 300, 196, -1));

        txtCodigoDistrito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoDistritoActionPerformed(evt);
            }
        });
        getContentPane().add(txtCodigoDistrito, new org.netbeans.lib.awtextra.AbsoluteConstraints(201, 334, 196, -1));

        txtCelular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCelularActionPerformed(evt);
            }
        });
        getContentPane().add(txtCelular, new org.netbeans.lib.awtextra.AbsoluteConstraints(201, 436, 196, -1));

        txtTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelefonoActionPerformed(evt);
            }
        });
        getContentPane().add(txtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(201, 402, 196, -1));

        txtEdad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEdadActionPerformed(evt);
            }
        });
        getContentPane().add(txtEdad, new org.netbeans.lib.awtextra.AbsoluteConstraints(201, 368, 196, -1));

        tblCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7", "Title 8", "Title 9", "Title 10"
            }
        ));
        tblCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblClienteMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblCliente);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 577, 729, 415));

        jLabel17.setIcon(new javax.swing.ImageIcon("C:\\Users\\Màximo\\Desktop\\DATANET\\DATANET\\IMAGENES\\VOLVER.png")); // NOI18N
        jLabel17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel17MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 20, -1, -1));

        jLabel1.setFont(new java.awt.Font("Roboto Medium", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("EMPLEADO");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, -1, -1));

        jLabel16.setIcon(new javax.swing.ImageIcon("C:\\Users\\Màximo\\Desktop\\DATANET\\DATANET\\IMAGENES\\FONDO.jpg")); // NOI18N
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 90));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 740, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1000, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 740, 1000));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtDNIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDNIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDNIActionPerformed

    private void txtRUCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRUCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRUCActionPerformed

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void txtAppatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAppatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAppatActionPerformed

    private void txtApmatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApmatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApmatActionPerformed

    private void txtDireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDireccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDireccionActionPerformed

    private void txtCodigoDistritoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoDistritoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoDistritoActionPerformed

    private void txtCelularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCelularActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCelularActionPerformed

    private void txtTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelefonoActionPerformed

    private void txtEdadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEdadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEdadActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        // TODO add your handling code here:}
        Conexion objConexion = new Conexion();
        clienteBL oClientes= recuperarDatosGUI();

        String strSentenciaInsert = String.format("INSERT INTO CLIENTES (Dni_Clientes, RUC_Clientes, Nom_Clientes, Appat_Clientes, Apmat_Clientes, Direc_Clientes, Cod_Distrito, Fnac_Clientes, Telef_Clientes, Cel_Clientes) VALUES ('%d', '%d', '%s', '%s', '%s', '%s', '%s', '%d', '%d', '%d')", oClientes.getDni_Clientes(), oClientes.getRUC_Clientes(), oClientes.getNom_Clientes(), oClientes.getAppat_Clientes(), oClientes.getApmat_Clientes(), oClientes.getDirec_Clientes(), oClientes.getCod_Distrito(), oClientes.getFnac_Clientes(), oClientes.getTelef_Clientes(), oClientes.getCel_Clientes());

        objConexion.ejecutarSentenciaSQL(strSentenciaInsert);
        this.mostrarDatos();
        this.limpiar();
    }//GEN-LAST:event_btnAgregarActionPerformed

    public void mostrarDatos() {
        while (mode1.getRowCount() > 0) {
            mode1.removeRow(0);
        }

        Conexion objConexion = new Conexion();
        try {
            ResultSet resultado = objConexion.consultarRegistros("SELECT * FROM CLIENTES");
            while (resultado.next()) {
                System.out.println(resultado.getString("Dni_Clientes"));
                System.out.println(resultado.getString("RUC_Clientes"));
                System.out.println(resultado.getString("Nom_Clientes"));
                System.out.println(resultado.getString("Appat_Clientes"));
                System.out.println(resultado.getString("Apmat_Clientes"));
                System.out.println(resultado.getString("Direc_Clientes"));
                System.out.println(resultado.getString("Cod_Distrito"));
                System.out.println(resultado.getString("Fnac_Clientes"));
                System.out.println(resultado.getString("Telef_Clientes"));
                System.out.println(resultado.getString("Cel_Clientes"));
                Object[] oClientes = {resultado.getString("Dni_Clientes"), resultado.getString("RUC_Clientes"), resultado.getString("Nom_Clientes"), resultado.getString("Appat_Clientes"), resultado.getString("Apmat_Clientes"), resultado.getString("Direc_Clientes"), resultado.getString("Cod_Distrito"), resultado.getString("Fnac_Clientes"), resultado.getString("Telef_Clientes"), resultado.getString("Cel_Clientes")};
                mode1.addRow(oClientes);
            }
        } catch (Exception e) {
            System.out.print(e);
        }
    }
    private void tblClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblClienteMouseClicked
        // TODO add your handling code here:
        if (evt.getClickCount() == 1) {
            JTable receptor = (JTable) evt.getSource();
            txtDNI.setText(receptor.getModel().getValueAt(receptor.getSelectedRow(), 0).toString());
            txtRUC.setText(receptor.getModel().getValueAt(receptor.getSelectedRow(), 1).toString());
            txtNombre.setText(receptor.getModel().getValueAt(receptor.getSelectedRow(), 2).toString());
            txtAppat.setText(receptor.getModel().getValueAt(receptor.getSelectedRow(), 3).toString());
            txtApmat.setText(receptor.getModel().getValueAt(receptor.getSelectedRow(), 4).toString());
            txtDireccion.setText(receptor.getModel().getValueAt(receptor.getSelectedRow(), 5).toString());
            txtCodigoDistrito.setText(receptor.getModel().getValueAt(receptor.getSelectedRow(), 6).toString());
            txtEdad.setText(receptor.getModel().getValueAt(receptor.getSelectedRow(), 7).toString());
            txtTelefono.setText(receptor.getModel().getValueAt(receptor.getSelectedRow(), 8).toString());
            txtCelular.setText(receptor.getModel().getValueAt(receptor.getSelectedRow(), 9).toString());
        }
        btnAgregar.setEnabled(false);
        btnModificar.setEnabled(true);
        btnEliminar.setEnabled(true);
    }//GEN-LAST:event_tblClienteMouseClicked

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:

        Conexion objetoConexion = new Conexion();
        clienteBL oClientes = recuperarDatosGUI();
        String strSentenciaInsert = String.format("DELETE FROM CLIENTES WHERE Dni_Clientes = '%d'", oClientes.getDni_Clientes());
        objetoConexion.ejecutarSentenciaSQL(strSentenciaInsert);
        this.mostrarDatos();
        this.limpiar();
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        // TODO add your handling code here:
        Conexion objetoConexion = new Conexion();

        clienteBL oCliente = recuperarDatosGUI();

        String strSentenciaInsert = String.format("UPDATE CLIENTES SET  RUC_Clientes='%d', Nom_Clientes='%s', Appat_Clientes='%s', Apmat_Clientes='%s',Direc_Clientes='%s',Cod_Distrito='%s',Fnac_Clientes='%d',Telef_Clientes='%d',Cel_Clientes='%d' "
                + "WHERE Dni_Clientes='%d'", oCliente.getRUC_Clientes(), oCliente.getNom_Clientes(), oCliente.getAppat_Clientes(), oCliente.getApmat_Clientes(), oCliente.getDirec_Clientes(), oCliente.getCod_Distrito(), oCliente.getFnac_Clientes(), oCliente.getTelef_Clientes(), oCliente.getCel_Clientes(), oCliente.getDni_Clientes());
        objetoConexion.ejecutarSentenciaSQL(strSentenciaInsert);
        this.mostrarDatos();
        this.limpiar();
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        this.limpiar();

    }//GEN-LAST:event_btnCancelarActionPerformed

    private void jLabel17MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel17MouseClicked
        INTERFAZ_2 f = new INTERFAZ_2();
        f.setVisible (true);
        this.dispose();
    }//GEN-LAST:event_jLabel17MouseClicked

    public void limpiar() {
        txtDNI.setText("");
        txtRUC.setText("");
        txtNombre.setText("");
        txtAppat.setText("");
        txtApmat.setText("");
        txtDireccion.setText("");
        txtCodigoDistrito.setText("");
        txtEdad.setText("");
        txtTelefono.setText("");
        txtCelular.setText("");

        btnAgregar.setEnabled(true);
        btnModificar.setEnabled(false);
        btnEliminar.setEnabled(false);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblCliente;
    private javax.swing.JTextField txtApmat;
    private javax.swing.JTextField txtAppat;
    private javax.swing.JTextField txtCelular;
    private javax.swing.JTextField txtCodigoDistrito;
    private javax.swing.JTextField txtDNI;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtEdad;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtRUC;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
